import type { NextPage } from 'next'
import Head from 'next/head'
import Login from '../components/layout/Login'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="header">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  )
}

export default Home
