<SafetyDriveApp>:
    orientation: 'vertical'
    Label:
        text: 'Client'
        font_size: '30sp'
        size_hint_y: '0.1'
    Camera:
        id: camera
        resolution: (1920, 1080)
        play: False
    ToggleButton:
        text: 'Start camera'
        on_press: root.play()
        size_hint_y: None
        height: '48dp'
    ToggleButton:
        text: 'Send video to S3'
        on_press: root.send_video_to_s3()
        size_hint_y: None
        height: '48dp'