FROM public.ecr.aws/lambda/python:3.6.2022.01.11.19

WORKDIR ${LAMBDA_TASK_ROOT}
RUN yum update -y

COPY src/serverless/lambda_serverless.py .
COPY requirements-serverless.txt .

RUN pip3 install -r requirements-serverless.txt
CMD ["lambda_serverless.lambda_handler"]