FROM public.ecr.aws/lambda/python:3.6.2022.01.11.19

WORKDIR ${LAMBDA_TASK_ROOT}
RUN yum update -y

COPY src/web_app/lambda_web_app.py .
COPY requirements-web-app.txt .

RUN pip3 install -r requirements-web-app.txt
CMD ["lambda_web_app.lambda_handler"]